### ISSUE TITLE
attempt to index upvalue 'FilteredMerchantItems' lua error

### ISSUE THREAD

**Issue by jrowles** [Sonaza/Vendorer#17]
Not 100% sure when it happens.

> 10x !Vendorer\vendorfilter.lua:127: attempt to index upvalue 'FilteredMerchantItems' (a nil value)
> [string "@!Vendorer\vendorfilter.lua"]:127: in function `GetMerchantItemLink'
> [string "@CorruptionTooltips\Modules\Icons.lua"]:220: in function `func'
> [string "@Ace3\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>
> 
> Locals:
> index = 10
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index upvalue 'FilteredMerchantItems' (a nil value)"
> FilteredMerchantItems = nil
> Addon = <table> {
>  TryHookUIErrors = <function> defined @!Vendorer\core.lua:1309
>  MakeTooltipString = <function> defined @!Vendorer\vendorfilter.lua:264
>  UpdateRepairButtons = <function> defined @!Vendorer\autorepair.lua:195
>  GetCurrentItemIgnoreList = <function> defined @!Vendorer\core.lua:1015
>  UpdateMerchantItems = <function> defined @!Vendorer\vendorfilter.lua:564
>  UpdateVendorerItemLists = <function> defined @!Vendorer\VendorerItemListsFrame.lua:111
>  ToggleCursorHighlights = <function> defined @!Vendorer\core.lua:446
>  MERCHANT_UPDATE = <function> defined @!Vendorer\core.lua:469
>  GetFreeBagSlotsForItem = <function> defined @!Vendorer\VendorerStackSplitFrame.lua:624
>  DoAutoRepair = <function> defined @!Vendorer\autorepair.lua:93
>  SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
>  IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
>  OpenQuickFiltersMenu = <function> defined @!Vendorer\vendorfilter.lua:724
>  ScanBindType = <function> defined @!Vendorer\core.lua:796
>  ScanContainers = <function> defined @!Vendorer\core.lua:723
>  IsValidClassArmorType = <function> defined @!Vendorer\core.lua:830
>  UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
>  db = <table> {
>  }
>  SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
>  FilterText = ""
>  PatchIgnoreListItems = <function> defined @!Vendorer\core.lua:689
>  GetMenuData = <function> defined @!Vendorer\settings.lua:94
>  OnEnable = <function> defined @!Vendorer\core.lua:334
>  GetItemLinkInfo = <function> defined @!Vendorer\vendorfilter.lua:184
>  GetQualityString = <function> defined @!Vendorer\vendorfilter.lua:745
>  GetCurrentExtension = <function> defined @!Vendorer\core.lua:531
>  OnInitialize = <function> defined @!Vendorer\core.lua:269
>  UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
>  ConfirmSellJunk = <function> defined @!Vendorer\core.lua:1326
>  IsRedText = <function> defined @!Vendorer\core.lua:809
>  OpenIgnoredItemsListsFrame = <function> defined @!Vendorer\core.lua:1159
>  GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
>  ConvertIgnoreList = <function> defined @!Vendorer\core.lua:665
>  name = "!Vendorer"
>  UpdateBuybackInfo = <function> defined @!Vendorer\core.lua:1982
>  AddMessage = <function> defined @!Vendorer\core.lua:415
>  Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
>  UpdateMerchantInfo = <function> defined @!Vendorer\core.lua:1808
>  RestoreSavedSettings = <function> defined @!Vendorer\core.lua:431
>  GetItemID = <function> defined @!Vendorer\core.lua:996
>  HideExtensionPanel = <function> defined @!Vendorer\core.lua:583
>  GetItemRepairCost = <function> defined @!Vendorer\autorepair.lua:29
>  GetMinimumSplitSize = <function> defined @!Vendorer\VendorerStackSplitFrame.lua:725
>  PlayerMoney = 3846479093
>  GetQualityIndex = <function> defined @!Vendorer\vendorfilter.lua:250
>  ResetAllFilters = <function> defined @!Vendorer\vendorfilter.lua:583
>  GetItemTooltipInfo = <function> defined @!Vendorer\core.lua:835
>  UnregisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153

**Comment by Sonaza** [comment]
Well seems the code was very dumb and occasionally nilled a table variable and then later using it without checking if it was nil.

Attempted a blind (untested) fix, hopefully it works.
