### ISSUE TITLE
Enhancement - Default ignore Items with benefits

### ISSUE THREAD

**Issue by fuba82** [Sonaza/Vendorer#3]
hi there,

maybe you can add some Items with passive Bonuses by default to the Ignorelist.

Items like:
[Gorepetal's Gentle Grasp](http://www.wowhead.com/item=116916)
[Peon's Mining Pick](http://www.wowhead.com/item=116913)
[Forager's Gloves](http://www.wowhead.com/item=86566/)

maybe you can take a look at [Auto Seller (former Salvage Yard Seller)](http://mods.curse.com/addons/wow/salvage-yard-seller)'s default Blacklist

greetings ;)

**Comment by Sonaza** [comment]
Sure thing. I was thinking of this before that it probably should have some.

**Comment by Sonaza** [comment]
Items added to the list, will go out in the next public release.

**Comment by fuba82** [comment]
thanks :)
