### ISSUE TITLE
You set itemEquipLoc, itemTexture and itemSellPrice are set globaly

### ISSUE THREAD

**Issue by fuba82** [Sonaza/Vendorer#6]
hi there,  
in your function:

```
local function FilterJunkItems(bagIndex, slotIndex)
```

you set:

```
itemEquipLoc, itemTexture, itemSellPrice = GetItemInfo(itemLink);
```

with this you set itemEquipLoc, itemTexture and itemSellPrice to global namespece.
if you set this values localy this will prevent some errors.

just change it to:

```
local itemEquipLoc, itemTexture, itemSellPrice = GetItemInfo(itemLink);
```

greeting, q3fuba

**Comment by Sonaza** [comment]
Actually it isn't, on the previous line there is a comma and I only just broke the long list on two lines to make it easier to read.

**Comment by fuba82** [comment]
ah damn!
you'r right i see...

sorry then :/
