### ISSUE TITLE
Maximum  currency-id is too low

### ISSUE THREAD

**Issue by yoshimo** [Sonaza/Vendorer#9]
The current maximum currency id is 1600
This leaves out at least these:

> 1602 Eroberung
> 1703 Währung für Schlachtfelder in 1. Saison von BFA
> 1704 Geistsplitter
> 1710 Seefahrerdublone
> 1716 Dienstmedaille der Eidgebundenen
> 1717 Dienstmedaille der 7. Legion
> 1718 Titanenresiduum

the last 4 are neccessary to filter properly in BFA.

**Comment by Sonaza** [comment]
Fixed.
